import { it, expect, vi } from 'vitest';
vi.mock('electron', () => ({ dialog: { showSaveDialog: vi.fn() } }));
vi.mock('child_process', () => ({ execFile: vi.fn() }));
vi.mock('fs', () => ({ default: { writeFileSync: vi.fn() }, writeFileSync: vi.fn() }));
vi.mock('./utils.js', () => {
  const _s = { columns: [], rowCount: 0, addRow() { this.rowCount++; }, getColumn() { return { numFmt: '', alignment: {}, eachCell() {} }; }, getRow() { return { height: 0, eachCell() {}, getCell() {} }; }, getCell() { return {}; }, eachRow() {}, mergeCells() {}, addImage() {} };
  const _w = { addWorksheet() { return _s; }, addImage() { return 1; }, xlsx: { writeFile() {}, load() {} }, worksheets: [] };
  return { createWorkbook: vi.fn(() => _w), createWorksheet: vi.fn(() => _s), saveWorkbook: vi.fn(async () => 'C:\\o.xlsx'), getAssetPath: vi.fn(() => 'C:\\a\\g.exe') };
});
vi.mock('./students.js', () => ({ groupPaymentsByStudentAndYear: vi.fn(), buildStudentRow: vi.fn(), getStudentColumns: vi.fn(), getStudentColumnsTemplate: vi.fn(), styleStudentSheet: vi.fn(), styleStudentSheetTemplate: vi.fn(), addSheetTitle: vi.fn(), paseStudentFile: vi.fn() }));
vi.mock('./expenses.js', () => ({ getExpensesColumns: vi.fn(), styleExpensesSheet: vi.fn() }));
vi.mock('./payments.js', () => ({ getPaymentsColumns: vi.fn(), buildPaymentRow: vi.fn(), stylePaymentSheet: vi.fn() }));
vi.mock('./receipt.js', () => ({ styleReceiptSheet: vi.fn() }));
vi.mock('./reports.js', () => ({ exportDelayByMonthReport: vi.fn(), exportDelayByTeacherReport: vi.fn() }));
import { saveWorkbook, getAssetPath } from './utils.js';
import { styleStudentSheet, styleStudentSheetTemplate, paseStudentFile, groupPaymentsByStudentAndYear, buildStudentRow } from './students.js';
import { styleExpensesSheet } from './expenses.js';
import { stylePaymentSheet } from './payments.js';
import { styleReceiptSheet } from './receipt.js';
import { exportDelayByMonthReport, exportDelayByTeacherReport } from './reports.js';
import { dialog } from 'electron';
import { execFile } from 'child_process';
import AppExcel from './excel.js';

it('all', async () => {
  const a = new AppExcel();
  expect(await a.exportReceiptToExcel(null)).toEqual({ success: false });
  saveWorkbook.mockResolvedValue('C:\\f.xlsx');
  await a.exportReceiptToExcel({ year: 2025, sequence: 1, amount: 15000 });
  expect(styleReceiptSheet).toHaveBeenCalled();
  saveWorkbook.mockResolvedValue(null);
  expect(await a.exportReceiptToExcel({ year: 2025, sequence: 1 })).toEqual({ success: false });
  saveWorkbook.mockResolvedValue('C:\\f.xlsx');
  expect(await a.exportReceiptToExcel({ year: 2025, sequence: 1 })).toEqual({ success: true, path: 'C:\\f.xlsx' });
  expect(await a.exportPaymentsByYearToExcel(null)).toEqual({ success: false });
  saveWorkbook.mockResolvedValue('C:\\p.xlsx');
  await a.exportPaymentsByYearToExcel({ name: '2025', paymentsFiltered: [{ id: 1 }] });
  expect(stylePaymentSheet).toHaveBeenCalled();
  expect(await a.exportExpensesByYearToExcel(null)).toEqual({ success: false });
  saveWorkbook.mockResolvedValue('C:\\e.xlsx');
  await a.exportExpensesByYearToExcel([]);
  expect(styleExpensesSheet).toHaveBeenCalled();
  expect(await a.exportStudentsByActiveToExcel([], [{}], ['2025'])).toEqual({ success: false, error: 'Estudiantes, Pagos o Años vacios.' });
  groupPaymentsByStudentAndYear.mockReturnValue({ 1: [] });
  buildStudentRow.mockReturnValue({ nombre: 'Juan' });
  saveWorkbook.mockResolvedValue('C:\\s.xlsx');
  await a.exportStudentsByActiveToExcel([{ id: 1 }], [{ id: 1, student_id: 1, year: '2025' }], ['2025']);
  expect(styleStudentSheet).toHaveBeenCalled();
  saveWorkbook.mockResolvedValue('C:\\t.xlsx');
  await a.exportTemplateStudents();
  expect(styleStudentSheetTemplate).toHaveBeenCalled();
  await expect(a.importStudentsFromExcel(null)).rejects.toThrow('Falta archivo Excel.');
  paseStudentFile.mockResolvedValue([{ nombre: 'Juan' }]);
  expect(await a.importStudentsFromExcel({ buffer: [1, 2, 3] })).toEqual({ success: true, students: [{ nombre: 'Juan' }] });
  saveWorkbook.mockResolvedValue(null);
  expect(await a.exportHistoric({ payments: null, years: null, students: null, expenses: null })).toEqual({ success: false });
  expect(await a.exportReportToExcel(null)).toEqual({ success: false });
  dialog.showSaveDialog.mockResolvedValue({ canceled: false, filePath: 'C:\\r.xlsx' });
  execFile.mockImplementation((_e, _a, cb) => cb(null, '', ''));
  expect(await a.exportReportToExcel([{ id: 1, amount: 100 }])).toEqual({ success: true });
  expect(getAssetPath).toHaveBeenCalledWith('excel-generator.exe');
  exportDelayByMonthReport.mockResolvedValue({ success: true });
  expect(await a.exportDelayByMonthReportToExcel({})).toEqual({ success: true });
  exportDelayByTeacherReport.mockResolvedValue({ success: false, error: 'x' });
  expect(await a.exportDelayByTeacherReportToExcel({})).toEqual({ success: false, error: 'x' });
});
